# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/soft/mine/peasantformer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/soft/mine/peasantformer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/soft/mine/peasantformer/CMakeFiles /home/user/soft/mine/peasantformer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/soft/mine/peasantformer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named core

# Build rule for target.
core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 core
.PHONY : core

# fast build rule for target.
core/fast:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/build
.PHONY : core/fast

#=============================================================================
# Target rules for targets named engine

# Build rule for target.
engine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 engine
.PHONY : engine

# fast build rule for target.
engine/fast:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/build
.PHONY : engine/fast

#=============================================================================
# Target rules for targets named peasantformer

# Build rule for target.
peasantformer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 peasantformer
.PHONY : peasantformer

# fast build rule for target.
peasantformer/fast:
	$(MAKE) -f CMakeFiles/peasantformer.dir/build.make CMakeFiles/peasantformer.dir/build
.PHONY : peasantformer/fast

src/Core/Core.o: src/Core/Core.cpp.o
.PHONY : src/Core/Core.o

# target to build an object file
src/Core/Core.cpp.o:
	$(MAKE) -f CMakeFiles/peasantformer.dir/build.make CMakeFiles/peasantformer.dir/src/Core/Core.cpp.o
.PHONY : src/Core/Core.cpp.o

src/Core/Core.i: src/Core/Core.cpp.i
.PHONY : src/Core/Core.i

# target to preprocess a source file
src/Core/Core.cpp.i:
	$(MAKE) -f CMakeFiles/peasantformer.dir/build.make CMakeFiles/peasantformer.dir/src/Core/Core.cpp.i
.PHONY : src/Core/Core.cpp.i

src/Core/Core.s: src/Core/Core.cpp.s
.PHONY : src/Core/Core.s

# target to generate assembly for a file
src/Core/Core.cpp.s:
	$(MAKE) -f CMakeFiles/peasantformer.dir/build.make CMakeFiles/peasantformer.dir/src/Core/Core.cpp.s
.PHONY : src/Core/Core.cpp.s

src/Core/CoreModules/Engine.o: src/Core/CoreModules/Engine.cpp.o
.PHONY : src/Core/CoreModules/Engine.o

# target to build an object file
src/Core/CoreModules/Engine.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/Core/CoreModules/Engine.cpp.o
.PHONY : src/Core/CoreModules/Engine.cpp.o

src/Core/CoreModules/Engine.i: src/Core/CoreModules/Engine.cpp.i
.PHONY : src/Core/CoreModules/Engine.i

# target to preprocess a source file
src/Core/CoreModules/Engine.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/Core/CoreModules/Engine.cpp.i
.PHONY : src/Core/CoreModules/Engine.cpp.i

src/Core/CoreModules/Engine.s: src/Core/CoreModules/Engine.cpp.s
.PHONY : src/Core/CoreModules/Engine.s

# target to generate assembly for a file
src/Core/CoreModules/Engine.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/Core/CoreModules/Engine.cpp.s
.PHONY : src/Core/CoreModules/Engine.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/peasantformer.dir/build.make CMakeFiles/peasantformer.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/peasantformer.dir/build.make CMakeFiles/peasantformer.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/peasantformer.dir/build.make CMakeFiles/peasantformer.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... core"
	@echo "... edit_cache"
	@echo "... engine"
	@echo "... peasantformer"
	@echo "... rebuild_cache"
	@echo "... src/Core/Core.o"
	@echo "... src/Core/Core.i"
	@echo "... src/Core/Core.s"
	@echo "... src/Core/CoreModules/Engine.o"
	@echo "... src/Core/CoreModules/Engine.i"
	@echo "... src/Core/CoreModules/Engine.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

