# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/soft/mine/peasantformer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/soft/mine/peasantformer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/soft/mine/peasantformer/CMakeFiles /home/user/soft/mine/peasantformer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/soft/mine/peasantformer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named modules_dirs

# Build rule for target.
modules_dirs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modules_dirs
.PHONY : modules_dirs

# fast build rule for target.
modules_dirs/fast:
	$(MAKE) -f CMakeFiles/modules_dirs.dir/build.make CMakeFiles/modules_dirs.dir/build
.PHONY : modules_dirs/fast

#=============================================================================
# Target rules for targets named opengl

# Build rule for target.
opengl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opengl
.PHONY : opengl

# fast build rule for target.
opengl/fast:
	$(MAKE) -f CMakeFiles/opengl.dir/build.make CMakeFiles/opengl.dir/build
.PHONY : opengl/fast

#=============================================================================
# Target rules for targets named peasantformer

# Build rule for target.
peasantformer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 peasantformer
.PHONY : peasantformer

# fast build rule for target.
peasantformer/fast:
	$(MAKE) -f CMakeFiles/peasantformer.dir/build.make CMakeFiles/peasantformer.dir/build
.PHONY : peasantformer/fast

#=============================================================================
# Target rules for targets named square

# Build rule for target.
square: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 square
.PHONY : square

# fast build rule for target.
square/fast:
	$(MAKE) -f CMakeFiles/square.dir/build.make CMakeFiles/square.dir/build
.PHONY : square/fast

src/Core.o: src/Core.cpp.o
.PHONY : src/Core.o

# target to build an object file
src/Core.cpp.o:
	$(MAKE) -f CMakeFiles/peasantformer.dir/build.make CMakeFiles/peasantformer.dir/src/Core.cpp.o
.PHONY : src/Core.cpp.o

src/Core.i: src/Core.cpp.i
.PHONY : src/Core.i

# target to preprocess a source file
src/Core.cpp.i:
	$(MAKE) -f CMakeFiles/peasantformer.dir/build.make CMakeFiles/peasantformer.dir/src/Core.cpp.i
.PHONY : src/Core.cpp.i

src/Core.s: src/Core.cpp.s
.PHONY : src/Core.s

# target to generate assembly for a file
src/Core.cpp.s:
	$(MAKE) -f CMakeFiles/peasantformer.dir/build.make CMakeFiles/peasantformer.dir/src/Core.cpp.s
.PHONY : src/Core.cpp.s

src/Engine/Engine.o: src/Engine/Engine.cpp.o
.PHONY : src/Engine/Engine.o

# target to build an object file
src/Engine/Engine.cpp.o:
	$(MAKE) -f CMakeFiles/peasantformer.dir/build.make CMakeFiles/peasantformer.dir/src/Engine/Engine.cpp.o
.PHONY : src/Engine/Engine.cpp.o

src/Engine/Engine.i: src/Engine/Engine.cpp.i
.PHONY : src/Engine/Engine.i

# target to preprocess a source file
src/Engine/Engine.cpp.i:
	$(MAKE) -f CMakeFiles/peasantformer.dir/build.make CMakeFiles/peasantformer.dir/src/Engine/Engine.cpp.i
.PHONY : src/Engine/Engine.cpp.i

src/Engine/Engine.s: src/Engine/Engine.cpp.s
.PHONY : src/Engine/Engine.s

# target to generate assembly for a file
src/Engine/Engine.cpp.s:
	$(MAKE) -f CMakeFiles/peasantformer.dir/build.make CMakeFiles/peasantformer.dir/src/Engine/Engine.cpp.s
.PHONY : src/Engine/Engine.cpp.s

src/Engine/IO/IO.o: src/Engine/IO/IO.cpp.o
.PHONY : src/Engine/IO/IO.o

# target to build an object file
src/Engine/IO/IO.cpp.o:
	$(MAKE) -f CMakeFiles/peasantformer.dir/build.make CMakeFiles/peasantformer.dir/src/Engine/IO/IO.cpp.o
.PHONY : src/Engine/IO/IO.cpp.o

src/Engine/IO/IO.i: src/Engine/IO/IO.cpp.i
.PHONY : src/Engine/IO/IO.i

# target to preprocess a source file
src/Engine/IO/IO.cpp.i:
	$(MAKE) -f CMakeFiles/peasantformer.dir/build.make CMakeFiles/peasantformer.dir/src/Engine/IO/IO.cpp.i
.PHONY : src/Engine/IO/IO.cpp.i

src/Engine/IO/IO.s: src/Engine/IO/IO.cpp.s
.PHONY : src/Engine/IO/IO.s

# target to generate assembly for a file
src/Engine/IO/IO.cpp.s:
	$(MAKE) -f CMakeFiles/peasantformer.dir/build.make CMakeFiles/peasantformer.dir/src/Engine/IO/IO.cpp.s
.PHONY : src/Engine/IO/IO.cpp.s

src/Engine/Phys/Phys.o: src/Engine/Phys/Phys.cpp.o
.PHONY : src/Engine/Phys/Phys.o

# target to build an object file
src/Engine/Phys/Phys.cpp.o:
	$(MAKE) -f CMakeFiles/peasantformer.dir/build.make CMakeFiles/peasantformer.dir/src/Engine/Phys/Phys.cpp.o
.PHONY : src/Engine/Phys/Phys.cpp.o

src/Engine/Phys/Phys.i: src/Engine/Phys/Phys.cpp.i
.PHONY : src/Engine/Phys/Phys.i

# target to preprocess a source file
src/Engine/Phys/Phys.cpp.i:
	$(MAKE) -f CMakeFiles/peasantformer.dir/build.make CMakeFiles/peasantformer.dir/src/Engine/Phys/Phys.cpp.i
.PHONY : src/Engine/Phys/Phys.cpp.i

src/Engine/Phys/Phys.s: src/Engine/Phys/Phys.cpp.s
.PHONY : src/Engine/Phys/Phys.s

# target to generate assembly for a file
src/Engine/Phys/Phys.cpp.s:
	$(MAKE) -f CMakeFiles/peasantformer.dir/build.make CMakeFiles/peasantformer.dir/src/Engine/Phys/Phys.cpp.s
.PHONY : src/Engine/Phys/Phys.cpp.s

src/Modules/Objects/Objects/Square.o: src/Modules/Objects/Objects/Square.cpp.o
.PHONY : src/Modules/Objects/Objects/Square.o

# target to build an object file
src/Modules/Objects/Objects/Square.cpp.o:
	$(MAKE) -f CMakeFiles/square.dir/build.make CMakeFiles/square.dir/src/Modules/Objects/Objects/Square.cpp.o
.PHONY : src/Modules/Objects/Objects/Square.cpp.o

src/Modules/Objects/Objects/Square.i: src/Modules/Objects/Objects/Square.cpp.i
.PHONY : src/Modules/Objects/Objects/Square.i

# target to preprocess a source file
src/Modules/Objects/Objects/Square.cpp.i:
	$(MAKE) -f CMakeFiles/square.dir/build.make CMakeFiles/square.dir/src/Modules/Objects/Objects/Square.cpp.i
.PHONY : src/Modules/Objects/Objects/Square.cpp.i

src/Modules/Objects/Objects/Square.s: src/Modules/Objects/Objects/Square.cpp.s
.PHONY : src/Modules/Objects/Objects/Square.s

# target to generate assembly for a file
src/Modules/Objects/Objects/Square.cpp.s:
	$(MAKE) -f CMakeFiles/square.dir/build.make CMakeFiles/square.dir/src/Modules/Objects/Objects/Square.cpp.s
.PHONY : src/Modules/Objects/Objects/Square.cpp.s

src/Modules/Render/OpenGL.o: src/Modules/Render/OpenGL.cpp.o
.PHONY : src/Modules/Render/OpenGL.o

# target to build an object file
src/Modules/Render/OpenGL.cpp.o:
	$(MAKE) -f CMakeFiles/opengl.dir/build.make CMakeFiles/opengl.dir/src/Modules/Render/OpenGL.cpp.o
.PHONY : src/Modules/Render/OpenGL.cpp.o

src/Modules/Render/OpenGL.i: src/Modules/Render/OpenGL.cpp.i
.PHONY : src/Modules/Render/OpenGL.i

# target to preprocess a source file
src/Modules/Render/OpenGL.cpp.i:
	$(MAKE) -f CMakeFiles/opengl.dir/build.make CMakeFiles/opengl.dir/src/Modules/Render/OpenGL.cpp.i
.PHONY : src/Modules/Render/OpenGL.cpp.i

src/Modules/Render/OpenGL.s: src/Modules/Render/OpenGL.cpp.s
.PHONY : src/Modules/Render/OpenGL.s

# target to generate assembly for a file
src/Modules/Render/OpenGL.cpp.s:
	$(MAKE) -f CMakeFiles/opengl.dir/build.make CMakeFiles/opengl.dir/src/Modules/Render/OpenGL.cpp.s
.PHONY : src/Modules/Render/OpenGL.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/peasantformer.dir/build.make CMakeFiles/peasantformer.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/peasantformer.dir/build.make CMakeFiles/peasantformer.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/peasantformer.dir/build.make CMakeFiles/peasantformer.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... modules_dirs"
	@echo "... opengl"
	@echo "... peasantformer"
	@echo "... rebuild_cache"
	@echo "... square"
	@echo "... src/Core.o"
	@echo "... src/Core.i"
	@echo "... src/Core.s"
	@echo "... src/Engine/Engine.o"
	@echo "... src/Engine/Engine.i"
	@echo "... src/Engine/Engine.s"
	@echo "... src/Engine/IO/IO.o"
	@echo "... src/Engine/IO/IO.i"
	@echo "... src/Engine/IO/IO.s"
	@echo "... src/Engine/Phys/Phys.o"
	@echo "... src/Engine/Phys/Phys.i"
	@echo "... src/Engine/Phys/Phys.s"
	@echo "... src/Modules/Objects/Objects/Square.o"
	@echo "... src/Modules/Objects/Objects/Square.i"
	@echo "... src/Modules/Objects/Objects/Square.s"
	@echo "... src/Modules/Render/OpenGL.o"
	@echo "... src/Modules/Render/OpenGL.i"
	@echo "... src/Modules/Render/OpenGL.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

